# Based on https://github.com/JakeWharton/RxBinding/blob/master/.travis.yml

language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-18;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install: ./gradlew ":cheesewire:assemble" --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew ":sample:assembleDebug" ":cheesewire:connectedCheck" ":cheesewire-conductor:connectedCheck" --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
